"""Aggregate measure_report.json runs into paper/data/summary.md.

Run: python paper/scripts/aggregate.py
"""
import json
import statistics
from pathlib import Path

DATA = Path(__file__).resolve().parent.parent / "data"

# Waterfall rows as scripts.measure names them (cumulative to the ear).
STAGES = [
    "STT finalize -> LLM",
    "LLM -> TTS (sentence-1 flush)",
    "TTS synth first chunk",
    "TTS -> bot-start (steady lead-hold)",
    "Transport + encode + network",
    "Browser jitter + decode + playout",
]


def p95(xs):
    xs = sorted(xs)
    return xs[max(0, min(len(xs) - 1, round(0.95 * (len(xs) - 1))))]


def load(lang):
    return [(f.name, json.loads(f.read_text(encoding="utf-8")))
            for f in sorted(DATA.glob(f"{lang}_run_*.json"))]


def summarize(lang):
    runs = load(lang)
    ttfos = [(name, r["meta"]["ttfo"]) for name, r in runs if r["meta"].get("ttfo")]
    vals = [t for _, t in ttfos]
    lines = [f"## {lang} ({len(runs)} runs)", ""]
    lines.append(f"- TTFO median **{statistics.median(vals):.2f}s** / p95 {p95(vals):.2f}s"
                 f" / min {min(vals):.2f}s / max {max(vals):.2f}s")
    lines.append("- per-run: " + ", ".join(f"{n.split('_run_')[1][:2]}:{t:.2f}" for n, t in ttfos))
    ears = [r["raw"]["anchors"].get("playout") for _, r in runs
            if r.get("raw", {}).get("anchors", {}).get("playout")]
    if ears:
        lines.append(f"- end-to-end to the ear (probe arrival + jitter est): median "
                     f"{statistics.median(ears):.2f}s over {len(ears)} runs")
    lines += ["", "| stage | median delta (s) | n |", "|---|---|---|"]
    for st in STAGES:
        ds = [row["delta"] for _, r in runs for row in r.get("waterfall", [])
              if row["stage"] == st and row["delta"] is not None]
        cell = f"{statistics.median(ds):.2f}" if ds else "unknown"
        lines.append(f"| {st} | {cell} | {len(ds)} |")
    fps = [r["raw"]["probe"]["recv_fps"] for _, r in runs if r["raw"]["probe"].get("recv_fps")]
    frz = [r["raw"]["probe"]["freeze_ms"] for _, r in runs if r["raw"]["probe"].get("freeze_ms")]
    if fps and frz:
        lines += ["", f"- received video fps median {statistics.median(fps):.1f}; max freeze {max(frz)}ms", ""]
    else:
        lines += ["", "- probe video rows missing", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    out = ["# Measurement summary (generated by aggregate.py -- do not hand-edit)", ""]
    for lang in ("zh", "en"):
        if list(DATA.glob(f"{lang}_run_*.json")):
            out.append(summarize(lang))
    (DATA / "summary.md").write_text("\n".join(out), encoding="utf-8")
    print("\n".join(out))
